const EndPoints = Object.freeze({
  AUTH: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    VERIFY_SETUP_TOKEN: "/auth/verify-setup-token",
    CREATE_PASSWORD: "/auth/create-password",
    FCM_TOKEN: "/auth/fcm-token",
    CHANGE_PASSWORD: "/auth/change-password",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
  },
  GROUPS: "/groups",
  GROUP_MEMBERS: (id) => `/groups/${id}/members`,
  GROUP_MEMBER: (groupId, memberId) => `/groups/${groupId}/members/${memberId}`,
  TRIPS: "/trips",
  TRIP: (id) => `/trips/${id}`,
  TRIP_HUB: (id) => `/trips/${id}/hub`,
  TRIP_BUDGET: (id) => `/trips/${id}/budget`,
  TRIP_EXPENSES: (id) => `/trips/${id}/expenses`,
  TRIP_EXPENSE: (tripId, id) => `/trips/${tripId}/expenses/${id}`,
  TRIP_TASKS: (id) => `/trips/${id}/tasks`,
  TRIP_TASK: (tripId, id) => `/trips/${tripId}/tasks/${id}`,
  TRIP_TASK_ACKNOWLEDGE: (tripId, id) => `/trips/${tripId}/tasks/${id}/acknowledge`,
  USER_PENDING_TASKS: "/tasks/pending",
  TRIP_VEHICLES: (id) => `/trips/${id}/vehicles`,
  TRIP_VEHICLE: (tripId, id) => `/trips/${tripId}/vehicles/${id}`,
  TRIP_ATTENDANCE: (id) => `/trips/${id}/attendance`,
  TRIP_ATTENDANCE_CHECKPOINTS: (id) => `/trips/${id}/attendance/checkpoints`,
  TRIP_ATTENDANCE_RECORD: (tripId, id) => `/trips/${tripId}/attendance/${id}`,
  TRIP_MEDIA: (id) => `/trips/${id}/media`,
  TRIP_MEDIA_ITEM: (tripId, id) => `/trips/${tripId}/media/${id}`,
  TRIP_POLLS: (id) => `/trips/${id}/polls`,
  TRIP_POLL_VOTE: (tripId, id) => `/trips/${tripId}/polls/${id}/vote`,
  TRIP_MEMBERS: (id) => `/trips/${id}/members`,
  TRIP_CHECKLISTS: (id) => `/trips/${id}/checklists`,
  TRIP_CHECKLIST_ITEM: (tripId, id) => `/trips/${tripId}/checklists/${id}`,
  TRIP_CHECKLIST_TOGGLE: (tripId, id) => `/trips/${tripId}/checklists/${id}/toggle`,
  TRIP_SCHEDULES: (id) => `/trips/${id}/schedules`,
  TRIP_SYNC: (id) => `/trips/${id}/sync`,
  ALARMS: "/alarms",
  ALARMS_ACTIVE: "/alarms/active",
  ALARMS_EMERGENCY: "/alarms/emergency",
  ALARMS_TEST_TRIGGER: "/alarms/test-trigger",
  ALARM_TRIGGER_NOW: (id) => `/alarms/${id}/trigger-now`,
  ALARM_STOP_CODE: (id) => `/alarms/${id}/stop-code`,
  ALARM_CANCEL: (id) => `/alarms/${id}/cancel`,
  ALARM_LOGS: (id) => `/alarms/${id}/logs`,
  ALARM_STOP: (id) => `/alarms/${id}/stop`,
  ALARMS_HISTORY: "/alarms/history",
  USERS: "/users",
  USER: (id) => `/users/${id}`,
  PROFILE: "/profile",
  POLLS: "/polls",
  POLL: (id) => `/polls/${id}`,
  POLL_VOTE: (id) => `/polls/${id}/vote`,
  POLL_ANALYTICS: (id) => `/polls/${id}/analytics`,
});

export default EndPoints;
